name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifact (mock debug)
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: app/build/outputs/apk/mock/debug/app-mock-debug.apk
    - name: Upload artifact (mock release)
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: app/build/outputs/apk/mock/release/app-mock-release.apk
    - name: Upload artifact (prod debug)
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: app/build/outputs/apk/production/release/app-production-release.apk
    - name: Upload artifact (prod release)
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: app/build/outputs/apk/production/release/app-production-release.apk
